### ISSUE TITLE
My Roadmap (mostly Gusto Specific)

### ISSUE THREAD

**Issue by wheeler** [wheeler/handlebars-to-jsx#4]
Running Command:
`tsc src/*.ts || true && clear && mv src/*.js dist/ || true && yarn test`

#### Support linkTo block helper
- [x] HTML children in custom block
- [ ] import Link (general import structure) (this would be over in the converter script)

#### NON BLOCK HELPERS that matter
- [x] linkTo nonBlock = 45
- [x] buttonWithIcon = 120
- [ ] ...field
  - [ ] modelTextField = 22
  - [ ] modelLabelTextField = 67
  - [ ] modelSelectField = 11
  - [ ] modelLabelSelectField = 45
  ~modelDateSelectField = 1 (collapsed)~
  - [ ] modelLabelDateSelectField = 6
  - [ ] modelRadioButtonField = 2
  - [ ] modelCheckBoxField = 5
  - [ ] modelHiddenField = 7
  - [ ] modelPayField = 5
  - [ ] modelPayFauxField = 1
  - [ ] modelFirstMiddleName = 5
  - [ ] modelLabelRadioButtonGroupField = 39
  - [ ] modelLabelPasswordField = 4
  - [ ] modelLabelDateField = 4
  - [ ] modelLabelDatePickerField = 8
  - [ ] modelLabelPercentOrAmountField = 2
  - [ ] modelLabelCurrencyField = 19
  - [ ] modifiedModelLabelCurrencyField = 11
  - [ ] selectField = 7
  - [ ] taxLabelSelectField = 1
  - [ ] checkBoxField = 1
  ~modelLongShortInput = 0~
- [ ] taxLabelCurrencyField = 2
- [ ] selectField = 7 (1 file)
- [ ] spinner = 70
- [ ] baseErrors = 43
- [ ] format[something] = 67 (general function calls + import)

#### BLOCK HELPERS that matter
- [x] linkTo = 98
- [ ] ifEqual = 22

#### NON BLOCK HELPERS that don't matter
- [ ] companyLinkTo = 5 (1 file)
- [x] externalLinkTo = 11
- [ ] buttonLinkWithIcon = 1
- [ ] renderPartial = 8
- [ ] htmlAddress = 2
- [ ] humanizeBoolean = 1

#### BLOCK HELPERS that don't matter
- [ ] key_value = 2
- [ ] externalLinkTo = 5

#### Base stuff that doesn't work
- [ ] with = 2 (refactor away)
- [ ] unless = 65
- [ ] divs instead of fragments?
- [ ] some fragments instead around single nodes

#### Generalize for opensource
- [x] function calls
- [x] call - resulting attribute is expression
- [x] call - resulting child is expression
- [x] block - resulting attribute is expression
- [x] block - resulting child is expression
- [x] customizable handlers for particular references and block handlers
- [ ] EXTRACT customizable handlers to options
